---
title: "Development and Building log/tools"
format: html
editor_options: 
  chunk_output_type: console
---

## r package dev - log
```{r, eval = FALSE}
# A log of package creation - do not run
#### Package setup ####
# usethis::create_package(getwd())
# usethis::use_agpl3_license()
# usethis::use_readme_rmd()
# usethis::use_tidy_contributing()
# usethis::use_tidy_coc()
# usethis::use_tidy_style()

#### Dependencies ####
# usethis::use_package("energyRt", type = "Depends", min_version = "0.50.0")
# usethis::use_package("sf", type = "Depends")
# usethis::use_package("ggplot2", type = "Imports")
# usethis::use_data_raw()

#### Vignettes & Articles ####
# usethis::use_article("data")
# usethis::use_article("maps")
# usethis::use_article("projects")
# usethis::use_article("usensys")
# usethis::use_article("us26")
# usethis::use_article("us50")
# usethis::use_article("ipm")
# usethis::use_article("ipmx")
# usethis::use_article("ReEDS")

#### Functions ####
# usethis::use_r("data")



```



## package website
```{r, eval = FALSE}
# run once:
# usethis::use_pkgdown()
# usethis::use_logo("archive/logo.svg")
# pkgdown::build_favicons(pkg = ".", overwrite = TRUE)
# pkgdown::init_site()
# pkgdown::template_navbar()
# usethis::use_github(private = FALSE)
# usethis::use_github_action("pkgdown")
# usethis::use_news_md()
# usethis::use_cran_badge()
# usethis::use_lifecycle_badge("experimental")

pkgdown::build_site_github_pages() # cleanups and builds the site
pkgdown::build_site() # builds the site and opens it in the browser
pkgdown::preview_site() # opens the site in the browser
```

## Datasets
```{r, eval = FALSE}
# maps ####
library(sf)
library(tidyverse)
# # mip_sf <- st_read(".../MIP/.../conus_26z_latlon_simple.geojson")
# mip_sf |> st_is_valid() |> all()
# 
# # Fix the geometry
# mip_sf_valid <- mip_sf |> 
#   st_transform("EPSG:3857") |>
#   st_make_valid() |> 
#   st_transform("EPSG:4326") 
# 
# mip_sf_valid |> st_is_valid() |> all()
# 
# us26_sf <- mip_sf_valid |> 
#   rename(ipm_reg_agg = region, region = model_region)
# 
# plot(us26_sf)
# us26_sf$region[us26_sf$region == "TRE_WEST"] <- "TREW"

# centroids <- us26_sf |>
#   st_centroid() |> 
#   st_coordinates() |>
#   as_tibble() |> 
#   rename(centr_lon = X, centr_lat = Y) 
# 
# us26_sf <- us26_sf |> cbind(centroids)
# save(us26_sf, file = "data-raw/us26_sf.RData")

set.seed(123)
us26_sf |>
  mutate(region_shuffle = factor(region, levels = sample(region), ordered = T)) |>
  ggplot() +
  geom_sf(aes(fill = region_shuffle), show.legend = F) +
  # geom_point(aes(x = centr_lon, y = centr_lat), color = "red", shape = 20) +
  geom_label(aes(x = centr_lon, y = centr_lat, label = region), size = 2) +
  scale_fill_viridis_d(option = "H") +
  labs(x = "", y = "") +
  theme_void()

```


